### ISSUE TITLE
Expose HTTP StatusCode for kongAPIError

### ISSUE THREAD

**Issue by hbagdi** [Kong/go-kong#10]
HTTP Status Code is embedded in the error string. There are times when the caller would like to know the error code and act accordingly (such as https://github.com/Kong/deck/pull/226).

https://github.com/Kong/go-kong/blob/main/kong/error.go

**Comment by krijohs** [comment]
I think I could help out with this one.
If kongAPIError is exported and a method named `Code` is added to the struct, the caller can use this method to get the code.
Would this be ok?

**Comment by hbagdi** [comment]
Yes, that seems reasonable.

**Comment by krijohs** [comment]
Great, just created the pull request.
