### ISSUE TITLE
Versions >3.1.1 require float TTL

### ISSUE THREAD

**Issue by rainest** [Kong/go-kong#251]
Unclear if this will require action. https://github.com/Kong/kong/issues/9944 is pending a response from the gateway team as to whether this change was intended or not.

At present, the master build of Kong (`kong/kong:master-alpine`) returns float values for key-auth TTLs. This breaks our struct, which expects an int. If the change is intended, we need to change it to a float. This should be fine for older version.

The upstream TTL change affects a generic TTL building block in the Kong DAO. It can be used in entities other than key-auth. It does not appear that go-kong is affected further, as no other tests are breaking, but we should do a review of Kong entities to confirm which use it and whether there are other go-kong structs that should require a change.

**Comment by mflendrich** [comment]
Apparently fixed by Kong/kong#9944
