### ISSUE TITLE
Don't leak unclosed body in `Client.Do()`

### ISSUE THREAD

**Issue by pmalek** [Kong/go-kong#276]
We seem to have a problem with is that we have an API: [`Client.Do()`](https://github.com/Kong/go-kong/blob/b5e8261e4507d18ab51d25c740152ada25466963/kong/client.go#L238) where we return a wrapper around `http.Response` where we don't close the body but it's already read (through `json.NewDecoder(resp.Body).Decode(v)`).

We should explicitly add a comment to that method that the response can be used to read e.g. the status code but the body will be completely read **BUT** the caller should close it nonetheless. Otherwise we might leak that.

**Comment by flabatut** [comment]
we're hitting that issue as well. We run a service that depends on go-kong module whose memory increase progressively. Is anyone already working on it or can we contribute ?

**Comment by pmalek** [comment]
Hi @flabatut 👋 

Thanks for your interest in this issue. I've submitted #348 to address this. You might want to take a look there.
