### ISSUE TITLE
Support for key-auth TTL

### ISSUE THREAD

**Issue by ivanRylach** [Kong/go-kong#3]
Hello,

`key-auth` supports TTL on keys with https://github.com/Kong/kong/pull/4984.

Are you planning to add the support of this functionality?

Thank you!

**Comment by ivanRylach** [comment]
@tjrivera and @hbagdi 
Thank you so much for fixing it!
Do you have an ETA for the new release?

**Comment by hbagdi** [comment]
Planning a release once #5 #4  are merged in.
