### ISSUE TITLE
Record default filler removes populated fields

### ISSUE THREAD

**Issue by rainest** [Kong/go-kong#307]
https://github.com/Kong/go-kong/pull/302 introduced a bug that was not visible until integrated into another application.

[bug.tar.gz](https://github.com/Kong/go-kong/files/11162123/bug.tar.gz) shows a demonstration using [deck](https://github.com/Kong/deck). Syncing `orig.yaml` with the current deck release (`/tmp/deck`) and then diffing with a build that includes 0.39.1 shows it removing the populated `config.add.headers` array.

**Comment by nishant95** [comment]
@rainest Sure, i'll look into it.

**Comment by nishant95** [comment]
raised a PR #309

**Comment by nishant95** [comment]
@rainest raised a PR #309 with the fix. 

Can we add some checks so that such bugs can be detected before merging the PR?

**Comment by rainest** [comment]
We can't easily add consistent checks beyond the style of tests already in this repo since it'd mean running other repo's tests.

I should have run a manual replace test like https://github.com/Kong/kubernetes-ingress-controller/pull/3866 earlier.

**Comment by nishant95** [comment]
Fixed in #309
