### ISSUE TITLE
Preserve explicit nulls in plugin configs

### ISSUE THREAD

**Issue by randmonkey** [Kong/go-kong#320]
## Problem

Changes in [#309](https://github.com/Kong/go-kong/pull/309) filled default values into fields of plugin configurations that are explicitly set to `null`. Some plugin supports `null`s in certain fields of their configurations, for example `datadog` plugin allows `null` in `host` to load host from environment variable. 

## Proposed solution
- do not fill in default value if a field is explicitly set to `nil`. (may be switched by params)

## Related issue:
-  https://github.com/Kong/kubernetes-ingress-controller/issues/3908

**Comment by mflendrich** [comment]
Not planned - decided against this change (and ensure that plugin schemas don't make a distinction between NULL and unset)
