### ISSUE TITLE
Install dependabot for go-kong

### ISSUE THREAD

**Issue by mflendrich** [Kong/go-kong#36]
Similarly to https://github.com/Kong/kubernetes-ingress-controller/pull/1059 , we need Dependabot in this repo as well, so that chores like #35 don't need manual work anymore.

**Comment by mmorel-35** [comment]
Would it also be pertinent to setup codecov, like it has been done for this [issue](https://github.com/Kong/kubernetes-ingress-controller/issues/835)?
