### ISSUE TITLE
ConsumerGroup UpdateRateLimitingAdvancedPlugin cannot be updated by ConsumerGroup name

### ISSUE THREAD

**Issue by shunsukew** [Kong/go-kong#381]
`AbstractConsumerGroupService`'s `UpdateRateLimitingAdvancedPlugin` method takes `nameOrID` as its second argument, so it is expected to be able to update rate limit config by ConsumerGroup name.
https://github.com/Kong/go-kong/blob/f062822dab7c67d10f0161d066d567f606a068c4/kong/consumer_group_service.go#L25

However, when calling this method with Consumer Group name, API returns status code 400 with message below.
```
{"code":3,"message":"validation error","details":[{"@type":"type.googleapis.com/kong.admin.model.v1.ErrorDetail","type":"ERROR_TYPE_FIELD","field":"consumer_group_id","messages":["must be a valid UUID"]}]}
```

In case passing UUID instead, the call will succeed.
Request should succeed with ConsumeGroup name as well.

I'm using Kong Konnect API.

**Comment by randmonkey** [comment]
Konnect does not support filling names in this API. It only support passing the ID (UUID) of the consumer group.
