### ISSUE TITLE
Incompatible with Kong Konnect

### ISSUE THREAD

**Issue by shunsukew** [Kong/go-kong#382]
There're many usecases users program calls Kong Konnect CP configuration endpoint.
However, some methods are incompatible with Kong Konnect API.

Kong Konnect client object and its implementation should be inside this repository instead of deck repository, so that users can use go binding codes easilly regardless of which endpoint to use (selfhosted Admin API or Kong Konnect API)
https://github.com/Kong/deck/tree/main/konnect

Also, some entities' CRUD will fail when name is passed instead of id (using go-kong binding code).
For example,
Getting Consumer by name succeeds
```
status 200
GET /v2/control-planes/{cp id}/core-entities/consumers/{consumer name}
```
Deleting Consumer by name fails
```
status 404
DELETE /v2/control-planes/{cp id}/consumers/{consumer name}
```

**Comment by pmalek** [comment]
Hi

Similarly as #383, go-kong is not meant to be used with Konnect but with Kong Gateway.

We're working on Go SDK for Konnect but it's not ready at this stage.
