### ISSUE TITLE
CI: use docker hub to setup kong in CI

### ISSUE THREAD

**Issue by hbagdi** [Kong/go-kong#50]
Bintray is going away, which means the CI will always be red.
The current CI also uses debian packages to set up Kong.
The scope here is
- update the CI script to not use Bintray
- use Docker in the CI to run Kong

**Comment by mmorel-35** [comment]
Maybe would it worth to try to define a github action for this : 

* https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
* https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action

This way it could be reused by go-kong and deck, at least.

**Comment by hbagdi** [comment]
@mmorel-35 We could use Github Actions here to solve the problem in the CI but then we will need a separate script to run the tests locally. Instead, if we write a script, we can use that in CI _and_ developer workflow, which helps with keeping different environments consistent.

**Comment by pmalek** [comment]
Not relevant anymore. Bintray is not used for quite some time. Related: https://github.com/Kong/go-kong/pull/55
