### ISSUE TITLE
Feature Request: Controller-Gen Compatibility

### ISSUE THREAD

**Issue by shaneutt** [Kong/go-kong#54]
Currently in the [Kong Kubernetes Ingress Controller (KIC)][kic] we use [controller-gen][cg] as a generator for manifests and libraries within the project.

Currently types within this repository are not explicitly compatible due to Floats, and so the following flag has to be used:

```
allowDangerousTypes=true
```

The purpose of this issue is to ledger a request that we modify the types in a future `go-kong` release such that we would start _intentionally maintaining explicit Kubernetes compatibility_.

[kic]:https://github.com/kong/kubernetes-ingress-controller
[cg]:https://github.com/kubernetes/code-generator

**Comment by mflendrich** [comment]
> such that we would start intentionally maintaining explicit Kubernetes compatibility

go-kong is a wrapper for Kong's API and the ultimate requirement is that types maintain explicit Kong compatibility.
If there are multiple types satisfying the Kong compatibility requirement, we can add a style guideline to prefer types that are convenient with Kubernetes. But I think that it's Kong that matters here most, not Kubernetes.

**Comment by mflendrich** [comment]
won't fix - this is a direct consequence of the type on Admin API

As @rainest pointed out, this is "dangerous" because roundtripping isn't reliable for floats.
