### ISSUE TITLE
Consumer update does not let username or custom_id be unset

### ISSUE THREAD

**Issue by andrew-bulford-form3** [Kong/go-kong#94]
The Kong Admin API allows the `username` and `custom_id` properties to be explicitly unset, by setting them to `null` when using the `PATCH` method, and will ignore values which aren't defined in the request body:
```
$ curl --silent -H'Content-Type: application/json' -X POST http://localhost:8001/consumers/ --data '{"username":"test-user"}' | jq
{
  "username": "test-user",
  "tags": null,
  "id": "a1adc2fa-962b-4540-ab55-32da4847425b",
  "custom_id": null,
  "created_at": 1633615986
}
$ curl --silent -H'Content-Type: application/json' -X PATCH http://localhost:8001/consumers/a1adc2fa-962b-4540-ab55-32da4847425b --data '{"custom_id":"test-id"}' | jq
{
  "username": "test-user",
  "tags": null,
  "id": "a1adc2fa-962b-4540-ab55-32da4847425b",
  "custom_id": "test-id",
  "created_at": 1633615986
}
$ curl --silent -H'Content-Type: application/json' -X PATCH http://localhost:8001/consumers/a1adc2fa-962b-4540-ab55-32da4847425b --data '{"username":null, "custom_id":"test-id2"}' | jq
{
  "username": null,
  "tags": null,
  "id": "a1adc2fa-962b-4540-ab55-32da4847425b",
  "custom_id": "test-id2",
  "created_at": 1633615986
}
$ curl --silent -H'Content-Type: application/json' -X PATCH http://localhost:8001/consumers/a1adc2fa-962b-4540-ab55-32da4847425b --data '{"username":"test-user", "custom_id":null}' | jq
{
  "username": "test-user",
  "tags": null,
  "id": "a1adc2fa-962b-4540-ab55-32da4847425b",
  "custom_id": null,
  "created_at": 1633615986
}
```

This behaviour doesn't work with the `ConsumerService` [Update](https://github.com/Kong/go-kong/blob/70471ece34623a56f799c81939ad465df0ff52ff/kong/consumer_service.go#L114) function, because it uses `PATCH` to update the consumer resource, but the `Consumer` [type](https://github.com/Kong/go-kong/blob/70471ece34623a56f799c81939ad465df0ff52ff/kong/types.go#L83) uses the `omitempty` annotation on the `custom_id` and `username` properties, so these properties are absent instead of `null` when not set.

This means there's no way to deliberately unset one of these properties:
* If you supply a pointer to an empty string this is marshalled as `""` which Kong rejects with a minimum length validation error
* If you leave it as a nil value the property is omitted from the marshalled JSON and ignored by Kong

I can think of a few options to fix this:
* Use PUT instead of PATCH when updating - this could unintentionally create a consumer if one with the specified ID doesn't exist
* Use custom JSON marshalling to render an empty string as `null`, rather than `""`, seeing as these properties can't be set to empty strings
* Remove `omitempty` from the type, though this would mean those values always need to be populated to avoid them being unset when updating

This might affect other resources, though I'm only concerned with the consume resource currently.

I'd be happy to submit a PR but am not familiar with the code base so thought it better to open this ticket for discussion.

**Comment by mflendrich** [comment]
We need to figure out how to distinguish between unset, empty and explicitly `null`ed fields first.

**Comment by rainest** [comment]
https://github.com/Kong/kong/issues/8093 indicates the Go JSON serializer maybe provides a way around this that doesn't have the potential unwanted side effects of the other options. At least for plugin configuration, including a field with _no_ value does send a `null` to the API.

Plugin configuration is possibly unique in that regard, since we have no dedicated type for it and it's handled as an opaque JSON blob, but I suppose that's worth trying. If you try and update a consumer from

```
kind: KongConsumer
metadata:
  name: foo
  annotations:
    kubernetes.io/ingress.class: kong
username: foo
custom_id: bar
```
to
```
kind: KongConsumer
metadata:
  name: foo
  annotations:
    kubernetes.io/ingress.class: kong
username: foo
custom_id:
```
does it null out the custom ID or send an empty string?

**Comment by mflendrich** [comment]
Closed as fixed
